### ISSUE TITLE
子域注册申请 [jntm]

### ISSUE THREAD

**Issue by yuanqidouya** [fuckccf/fuckccf.github.io#1]
### 类型

A

### 值

43.156.62.99

**Comment by dsy4567** [comment]
已收到

**Comment by dsy4567** [comment]
@zhegeshijieshangzuishuaideren

**Comment by zhegeshijieshangzuishuaideren** [comment]
请说明该子域与您的关系（您只能注册与您的 GitHub/洛谷用户名(支持中文)相同的子域）

**Comment by zhegeshijieshangzuishuaideren** [comment]
https://github.com/fuckccf/fuckccf.github.io/issues/new/choose 新的 .ghp.fucksc.cf可以试试

**Comment by zhegeshijieshangzuishuaideren** [comment]
http://jntm.fucksc.cf/ 注册成功, 恭喜恭喜 🎉

**Comment by zhegeshijieshangzuishuaideren** [comment]
晚上好呀，贵站是不是该放点东西了
