### ISSUE TITLE
子域注册申请 zhuqiaoying

### ISSUE THREAD

**Issue by Molmin** [fuckccf/fuckccf.github.io#12]
### 类型

CNAME（域名）

### 值

https://zhuqiaoying.github.io

### 套 Cloudflare 代理加速访问

- [ ] 为我的网站套 Cloudflare 代理

**Comment by zhegeshijieshangzuishuaideren** [comment]
请将 `[要注册的子域，最少 4 个字符]` 修改为任意字符，例如你的 GitHub 用户名

**Comment by zhegeshijieshangzuishuaideren** [comment]
http://zhuqiaoying.fucksc.cf/ 注册成功，恭喜
如果要注册的子域不正确，请在下方回复

**Comment by Molmin** [comment]
访问 http://zhuqiaoying.fucksc.cf/ 后跳转到 https://zhuqiaoying.fucksc.cf/ 

然后浏览器提示：

你的连接不是专用连接
攻击者可能试图从 zhuqiaoying.fucksc.cf 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_COMMON_NAME_INVALID
zhuqiaoying.fucksc.cf 使用加密来保护你的信息。这次，当 Microsoft Edge 尝试连接到 zhuqiaoying.fucksc.cf 时，网站发回了不正常和不正确的凭据。如果攻击者尝试假冒 zhuqiaoying.fucksc.cf，或者 WLAN 登录屏幕已中断连接，则可能会发生这种情况。你的信息仍然安全，因为在交换任何数据之前，Microsoft Edge 停止了连接。

你现在无法访问 zhuqiaoying.fucksc.cf，因为网站使用的是 HSTS。网络错误和攻击通常是暂时的，因此该页面以后可能会恢复正常。

如何解决此问题？我没有此类经验，能否给予一些指导？谢谢。

**Comment by zhegeshijieshangzuishuaideren** [comment]
出于安全和隐私考虑，`fucksc.cf` 及所有子域均已强制只能通过 HTTPS 访问。
可以打开仓库设置 > Pages > 重新修改 `Custom domain` 并勾选 `Enforce HTTPS`，然后试试看

**Comment by Molmin** [comment]
Now it works. Thanks!
