### ISSUE TITLE
子域注册申请 `ych.immccn123`

### ISSUE THREAD

**Issue by immccn123** [fuckccf/fuckccf.github.io#3]
### 类型

跳转至自定义 url

### 值

https://ych-tools.immccn123.xyz/

### 其他说明

洛谷UID: 385633

**Comment by zhegeshijieshangzuishuaideren** [comment]
https://ych.immccn123.fucksc.cf/ 注册成功，恭喜  
注意：需要等待一段时间才能正常访问
