### ISSUE TITLE
子域注册申请 [rapesand]

### ISSUE THREAD

**Issue by chenyuanxi11** [fuckccf/fuckccf.github.io#9]
### 类型

CNAME

### 值

https://vochant.github.io

### 套 Cloudflare 代理加速访问

- [ ] 为我的网站套 Cloudflare 代理

### 其他说明

r***s，懂的都懂

**Comment by zhegeshijieshangzuishuaideren** [comment]
https://rapesand.fucksc.cf/
已添加子域，但你似乎没有正确配置 GitHub Pages 的 CNAME，请尽快更新配置，或将子域类型改为跳转至自定义 url
